return {
  {
    "folke/which-key.nvim",
    opts = {
      spec = {
        { "<space>/", icon = "🔍" },

        -- Vlime mappings (lisp filetype)
        { "<localleader>c", group = "Connection", ft = "lisp" },
        { "<localleader>cc", desc = "Connect to server", ft = "lisp" },
        { "<localleader>cs", desc = "Switch connections", ft = "lisp" },
        { "<localleader>cd", desc = "Disconnect", ft = "lisp" },
        { "<localleader>cR", desc = "Rename connection", ft = "lisp" },

        { "<localleader>r", group = "Server/REPL", ft = "lisp" },
        { "<localleader>rr", desc = "Run new server", ft = "lisp" },
        { "<localleader>rv", desc = "View server console", ft = "lisp" },
        { "<localleader>rV", desc = "View selected server", ft = "lisp" },
        { "<localleader>rs", desc = "Stop current server", ft = "lisp" },
        { "<localleader>rS", desc = "Stop selected server", ft = "lisp" },
        { "<localleader>rR", desc = "Rename server", ft = "lisp" },
        { "<localleader>rt", desc = "Restart server", ft = "lisp" },
        { "<localleader>rc", desc = "Clear REPL", ft = "lisp" },

        { "<localleader>s", group = "Send to REPL", ft = "lisp" },
        { "<localleader>ss", desc = "Send expr/atom at cursor", ft = "lisp" },
        { "<localleader>se", desc = "Send expression", ft = "lisp" },
        { "<localleader>st", desc = "Send top-level expression", ft = "lisp" },
        { "<localleader>sa", desc = "Send atom", ft = "lisp" },
        { "<localleader>si", desc = "Send snippet", ft = "lisp" },

        { "<localleader>m", group = "Macro expand", ft = "lisp" },
        { "<localleader>mm", desc = "Expand macro", ft = "lisp" },
        { "<localleader>m1", desc = "Expand macro once", ft = "lisp" },
        { "<localleader>ma", desc = "Expand all macros", ft = "lisp" },

        { "<localleader>o", group = "Compile", ft = "lisp" },
        { "<localleader>oe", desc = "Compile expression", ft = "lisp" },
        { "<localleader>ot", desc = "Compile top-level expression", ft = "lisp" },
        { "<localleader>of", desc = "Compile file", ft = "lisp" },

        { "<localleader>x", group = "Cross-reference", ft = "lisp" },
        { "<localleader>xc", desc = "Show callers", ft = "lisp" },
        { "<localleader>xC", desc = "Show callees", ft = "lisp" },
        { "<localleader>xr", desc = "Show references", ft = "lisp" },
        { "<localleader>xb", desc = "Show bindings", ft = "lisp" },
        { "<localleader>xs", desc = "Show setters", ft = "lisp" },
        { "<localleader>xe", desc = "Show macro callers", ft = "lisp" },
        { "<localleader>xm", desc = "Show specialized methods", ft = "lisp" },
        { "<localleader>xd", desc = "Show definition", ft = "lisp" },
        { "<localleader>xi", desc = "Xref interactive", ft = "lisp" },

        { "<localleader>d", group = "Describe/Documentation", ft = "lisp" },
        { "<localleader>do", desc = "Describe operator", ft = "lisp" },
        { "<localleader>da", desc = "Describe atom", ft = "lisp" },
        { "<localleader>di", desc = "Describe interactive", ft = "lisp" },
        { "<localleader>ds", desc = "Apropos search", ft = "lisp" },
        { "<localleader>dd", group = "Documentation", ft = "lisp" },
        { "<localleader>ddo", desc = "Documentation for operator", ft = "lisp" },
        { "<localleader>dda", desc = "Documentation for atom", ft = "lisp" },
        { "<localleader>ddi", desc = "Documentation interactive", ft = "lisp" },
        { "<localleader>dr", desc = "Show arglist", ft = "lisp" },

        { "<localleader>I", group = "Inspect", ft = "lisp" },
        { "<localleader>Ii", desc = "Inspect expr/atom", ft = "lisp" },
        { "<localleader>Ie", desc = "Inspect expression", ft = "lisp" },
        { "<localleader>It", desc = "Inspect top-level expr", ft = "lisp" },
        { "<localleader>Ia", desc = "Inspect atom", ft = "lisp" },
        { "<localleader>Is", desc = "Inspect symbol", ft = "lisp" },
        { "<localleader>In", desc = "Inspect snippet", ft = "lisp" },

        { "<localleader>T", group = "Trace", ft = "lisp" },
        { "<localleader>Td", desc = "Trace dialog", ft = "lisp" },
        { "<localleader>Ti", desc = "Trace/untrace interactive", ft = "lisp" },
        { "<localleader>Tt", desc = "Trace/untrace at cursor", ft = "lisp" },

        { "<localleader>u", group = "Undefine", ft = "lisp" },
        { "<localleader>uf", desc = "Undefine function", ft = "lisp" },
        { "<localleader>us", desc = "Unintern symbol", ft = "lisp" },
        { "<localleader>ui", desc = "Undefine interactive", ft = "lisp" },

        { "<localleader>w", group = "Windows", ft = "lisp" },
        { "<localleader>wp", desc = "Close preview", ft = "lisp" },
        { "<localleader>wr", desc = "Close arglist", ft = "lisp" },
        { "<localleader>wn", desc = "Close notes", ft = "lisp" },
        { "<localleader>wR", desc = "Close REPL", ft = "lisp" },
        { "<localleader>wA", desc = "Close all Vlime windows", ft = "lisp" },
        { "<localleader>wl", desc = "Choose window to close", ft = "lisp" },

        { "<localleader>i", desc = "Interaction mode", ft = "lisp" },
        { "<localleader>l", desc = "Load file", ft = "lisp" },
        { "<localleader>a", desc = "Disassemble", ft = "lisp" },
        { "<localleader>p", desc = "Set package", ft = "lisp" },
        { "<localleader>b", desc = "Set breakpoint", ft = "lisp" },
        { "<localleader>t", desc = "List threads", ft = "lisp" },
        { "<localleader>?", desc = "Quick reference", ft = "lisp" },
      },
    },
  },
}
